### PR TITLE
Get MacOS Dasher building and working in 64-bit

### PR DESCRIPTION
**Pull request by sebwills**
The changes in the first commit, 9462c61, were emailed to me by Jorge Tendeiro who sponsored a developer to upgrade the MacOS build to 64-bit, so we now have a MacOS version of Dasher 5!

Subsequent commits in this PR are me tidying up a few of the changes and fixing some bugs I noticed.

### CODE REVIEW

**Comment by willwade** [comment]
Nice! Just to confirm - when you build it - is it looking like this: 
Screenshot 2020-04-07 at 17 51 35

**Comment by cagdasgerede** [comment]
Could you also update README.md file of the project? There are some comments about there for MacOS platform which may need some updates. Also, should we have a Install.MacOS file like the other platforms (Install.Linux, Install.Windows etc.)?

**Comment by sebwills** [comment]
@willwade No, the canvas fills the window vertically for me:
image
Is your screenshot what you are seeing when building from this source?

I have noticed a conceivably related issue which is that the Dasher font in Preferences is set to 'no value' for each new user until they select a font (which is then persisted), and 'no value' seems to make it render a small and blurry font. I am intending to raise a github issue for that  (and hopefully fix it in another PR). And I think some (all?) of the preferences aren't being saved at all. Also planning to investigate separately.

**Comment by willwade** [comment]
> @willwade No, the canvas fills the window vertically for me:
> 
> image
> 
> Is your screenshot what you are seeing when building from this source?
> 

Yeah. That’s wierd. I’ll try looking at why that maybe then. Hmm. 

@cagdas - I can try and figure out circleCI. You basically open the Dasher.xcodeproj file and hit the build button. There’s a command line to do that too.

**Comment by sebwills** [comment]
I've updated the README and added an INSTALL.macOS which contains the sum total of my knowledge about how to build it :)

**Comment by sebwills** [comment]
Re circleCI, note that https://circleci.com/docs/2.0/oss/ says:

> To support the open source community, organizations on Github or Bitbucket will be given 100,000 free credits per week that ... can be spent on Linux-medium resources.

> Note: If you are building an open source project on macOS, contact billing@circleci.com to enable these additional containers.

**Comment by cagdasgerede** [comment]
Created an Issue for circleci build for MacOS here: #172

**Pull request merged**
