### PR TITLE
Fixed Win32 Option to turn on/off box outline

### PR DESCRIPTION
**Pull request by furkandinc**
Ref: #82 
I fixed box outline bug by adding simple condition.

### CODE REVIEW

**Comment by modernuniverse** [comment]
@furkandinc 
Could you add a small demo video showing that when the option is selected, the boxes are not drawn?

**Comment by furkandinc** [comment]
Here is the demo showing gray outlines are not drawn when the option is not selected: https://youtu.be/ZwvBXwOYjlk

**Comment by cagdasgerede** [comment]
I cannot tell what the difference is from the video. Can you clarify?

**Comment by furkandinc** [comment]
Changed outline color from gray to red for the demo to see the difference.
2018-03-21 22_58_54-2018-03-21_22-58-33 txt - dasher

**Comment by furkandinc** [comment]
Another demo with high quality: https://youtu.be/1RNOTJCX-W8

**Pull request merged**
